### ISSUE TITLE
Feature request: save and load mod configs

### ISSUE THREAD

**Issue by judge2020** [Wurst-Imperium/Wurst-MC-1.10#20]
I hope feature requests are allowed as issues.

This feature would add the commands `.load <config1>` and `.save <config2>`. What .save does is saves the currently active mods to some sort of config file, then .load will load a saved config. This can be useful for different servers, as some mods work depending on their plugins. 

Things to keep in mind:
- If the type of mod has parameters, such as killaura does, it should save those
- Should save the type of YesCheat loaded

Otherwise, it should be a simple list of mods in a config file.

**Comment by kamron030702** [comment]
it should also have the feature to add, remove, and list mods that are in a saved config
