### ISSUE TITLE
Advanced Anti Cheat addition to yescheat plus

### ISSUE THREAD

**Issue by masrourmouad** [Wurst-Imperium/Wurst-MC-1.10#23]
please add Anticheat plus  to yescheat plus , thanks

**Comment by CisBetter** [comment]
**Is AntiCheat+ actively maintained (they say it is for 1.7.10 / last update 2015)?** I have tried [AntiCheatPlus v 2.1.4](https://www.spigotmc.org/resources/anticheatplus.2714/) with my Spigot 1.10 server and it did not seem to work at all.

--
# **OR**

Did you mean Advanced Anti Cheat (AAC)(e.g. floating **invisible NPCs** that detect KillAura)?
If so :fast_forward: please rename this issue to "`Advanced Anti Cheat addition to YesCheat+`" or equal.

If I am wrong and AntiCheat+ is available for 1.10 please let me know :smile:

**Comment by GravelCZLP** [comment]
AntiCheat+ is not for 1.10 he means the AAC (the NPC thing) and i have an idea how to bypass it. but it has 8 ways of detecting Killaura. I will wait until konsolas releases AAC3 and then goto bypasses.

**Comment by yellowlight2** [comment]
As far is I know AAC3 is already running on "gommehd.net"
