### ISSUE TITLE
Configurable Block ESP similar to xray

### ISSUE THREAD

**Issue by MattSturgeon** [Wurst-Imperium/Wurst-MC-1.10#30]
An ESP mod that functions like chest ESP but allows you to choose which blocks, like xray, would be really useful for finding things like portals, farms or bases without actively looking for them with xray/basefinder.

It would be good if you could set the colour for each block seperately, and/or have a mode where the block's particle colour is used as the default.

In theory this could be an expansion/replacement of chest ESP

**Comment by sudofox** [comment]
> In theory this could be an expansion/replacement of chest ESP

do note that chestESP functions by checking the loaded tile entity list (`mc.theWorld.loadedTileEntityList`), while blockESP has to do a far more costly iteration over each block in the loaded chunks. This is mitigated partially by the three-second delay between updates that you see in the Search and BaseFinder mods, but even with that, there is still a noticeable lag between updates the larger you set the scan radius to.
