### ISSUE TITLE
Contacting Alex re: Step and Map request

### ISSUE THREAD

**Issue by swaith** [Wurst-Imperium/Wurst-MC-1.10#33]
NOT AN ISSUE,

Sorry Alex, no other way to contact you after a quick google search (my skype is Swaith07) 

I wanted to ask how to stop the autostepup on blocks -im a returning player and it doesn't appear to be an option iv used or default client so thought id ask, the other issue of the same name is closed with no reply, sorry to open a new one for the same thing.

Also I wanted to ask if there is anyway to add one of the various map mods into profile? (as in can I do it without it ruining the client?) - this also falls under way-points similarly closed previously 

Also - is there a way to donate? its a great client and I love your work =]

Kind regards, 

Swaith

**Comment by CisBetter** [comment]
Did you check that Minecraft's vanilla AutoStep is disabled?
    In-Game: Options > Controls > Auto-jump: ON
    
![tmp1](https://cloud.githubusercontent.com/assets/17952058/19603392/3c1ec2e8-97b1-11e6-865f-93e26af04dd2.png)
