### ISSUE TITLE
Guardian temple

### ISSUE THREAD

**Issue by marcocorriero** [Wurst-Imperium/Wurst-MC-1.10#40]
Why you dont code something to detects Monument in deserts / oceans 

For oceans : Guardians Temple

and deserts too (desert monuments)

**Comment by Alexander01998** [comment]
It's called BaseFinder.

**Comment by marcocorriero** [comment]
i tried with basefinder, and it tooks me some hour to find one, seems basefinder is bugged @Alexander01998
