### ISSUE TITLE
Keybind for LCONTROL reappears on start, custom GUI keybind is already set

### ISSUE THREAD

**Issue by antsuke42** [Wurst-Imperium/Wurst-MC-1.10#41]
I understand the reasoning behind #12, but i have set the GUI keybind to LMENU, and i use LCONTROL to sprint! I don't want to remove it every start.
Maybe have a option to disable #12?

**Comment by CisBetter** [comment]
I think #42 should fix your problem:
Wurst tries to add a keybind if it doesn't find an existing one (e.g. LMENU). There was a bug causing Wurst to not detect any existing keybinds. With this fix (#42) your keybind should get recognized and no second keybind should be added.
(At least working for my RSHIFT keybind :smile:)
-- CisBetter
