### ISSUE TITLE
Code for Fly Latest NCP, Killaura

### ISSUE THREAD

**Issue by EmeraldTheDev** [Wurst-Imperium/Wurst-MC-1.10#52]
Im wondering if i can get the code for it and Killaura - For the Client Cryton

**Comment by CisBetter** [comment]
If Cryton and its source code are publicly available, it is published under the same license as Wurst, and all other conditions of the [Mozilla Public License 2.0](https://mozilla.org/MPL/2.0/) are met you can. For more information on using Wurst's source code please visit the FAQ: [Can I use Wurst's source code in my own hacked client?](https://www.wurst-client.tk/faq/can-i-use-the-source-code/)

PS: Having a look at the FAQ is always a good thing to do before asking a question :smile:

**Comment by Alexander01998** [comment]
What @CisBetter said.
