### ISSUE TITLE
Navigator Layout

### ISSUE THREAD

**Issue by yellowlight2** [Wurst-Imperium/Wurst-MC-1.10#58]
The Layout of modules screens in the navigator is totally messed up.

Those screens (or the text to be more precise) are implemented very bad.
I think the whole navigator should be refactored.

![screenshot_20161113_031024](https://cloud.githubusercontent.com/assets/16945485/20243212/cb6c84d6-a94e-11e6-856a-d17729869859.png)

**Comment by Alexander01998** [comment]
Possible causes & solutions:

|Cause|Solution|
|---|---|
|Your OS just can't render fonts properly.|Just use Windows and you'll be fine.|
|You are using the developer version of Wurst at an old commit where the font was actually messed up like that. (I see you have Eclipse open in the background.)|Use the latest version instead.|
|You don't have a proper installation of the Segoe UI font.|Get a fresh installation of Segoe UI.|
|Your graphics card is outdated or broken.|Update the drivers or use a different graphics card.|

**Comment by yellowlight2** [comment]
I think I will recode the gui at some time...

Just using one String and do the layout by using line feeds is a horrible solution.
The GUI and the modules could be way more decoupled.
