### ISSUE TITLE
Project 'Wurst MC 1.10' is missing required library: 'game-output/versions/1.10/1.10.jar'

### ISSUE THREAD

**Issue by 439856sefesfsefe9356qc943** [Wurst-Imperium/Wurst-MC-1.10#64]
Because im kind of outdated related to Minecraft i dont know where i can find the folder 'game-output'.
Eclipse is giving me this error: 

> Project 'Wurst MC 1.10' is missing required library: 'game-output/versions/1.10/1.10.jar'

Please give me a brief explanation on how i can find it or where i get it.

Thank you.

**Comment by yellowlight2** [comment]
That's the file from ".minecraft/versions/1.10/1.10.jar"

**Comment by 439856sefesfsefe9356qc943** [comment]
@yellowlight2 First of all this helped and the error is gone huge thanks for that.
BUT now im gettig 100 new errors ([...] is not visible).
Of course i know how to get rid of them and what they say but WHY do i get them. I mean is it a bug in the release or did i do something wrong?
Attached you can find the structure of my Wurst folder.
[tree.txt](https://github.com/Wurst-Imperium/Wurst-MC-1.10/files/589992/tree.txt)

**Comment by CisBetter** [comment]
Make sure you've applied the patch:
> 4. Go to the patch folder and run initialize.bat.

**Comment by DesWurstes** [comment]
Nah, go to project properties, choose libraries tab, select the 1.10.jar, press "edit" and choose the 1.10 jar in your PC.

**Comment by 439856sefesfsefe9356qc943** [comment]
@DesWurstes I did exactly what you say and it still doesnt work. After reimporting the project AND @CisBetter of course running the initialize patch (i am able to read a readme). I dont really have fatal but a bunch of easy fixable errors -> http://i.imgur.com/nO8XAHb.png
What i want to know is if yo got the same errors or if there is a bug in the source. 
If its a broken source id be glad if you could upload a working project.

**Comment by CisBetter** [comment]
I get the exact same errors as you if the patch is not applied:
![capture](https://cloud.githubusercontent.com/assets/17952058/20322909/0f84599a-ab7b-11e6-9ebf-4c2ff89c7d89.PNG)
Therefore I think the patch CANNOT be applied correctly (this sometimes happens if you're running the batch file in eclipse). Could you open the **Git Bash** // your Shell in `mc` and post the output of 
``` Shell
git status
```
and
``` Shell
git log
```

**Comment by yellowlight2** [comment]
Can you edit the initialize.bat file.
Go to the line with the apply command and add "-v".
It should look like that:
"git apply --ignore-space-change --ignore-whitespace ..\patch\minecraft.patch -v"

Run the modified batch-file again in cmd.exe and post the output.

**Comment by 439856sefesfsefe9356qc943** [comment]
I assume i did anything wrong. I ran the 'patch.bat' with the regular explorer.

[log.txt](https://github.com/Wurst-Imperium/Wurst-MC-1.10/files/595538/log.txt)
[status.txt](https://github.com/Wurst-Imperium/Wurst-MC-1.10/files/595539/status.txt)

Is it correct to place the 34.jar files directly into the /lib folder (no subfolders).
Except of this i have no idea what i could have done wrong.

**Comment by CisBetter** [comment]
1. Is this really the output of git in `mc`. If not, please post git status' and git log's output in your `mc` folder (Minecraft's Source Code). If you get any error from that the apply-patch script didn't work properly.
2. Yes, you've got to copy the jar files into lib (not the folder structure).

**Comment by 439856sefesfsefe9356qc943** [comment]
@CisBetter Thank you for your patience with me.
These should be the roght files
[log inside mc.txt](https://github.com/Wurst-Imperium/Wurst-MC-1.10/files/599965/log.inside.mc.txt)
[status inside mc.txt](https://github.com/Wurst-Imperium/Wurst-MC-1.10/files/599966/status.inside.mc.txt)

**Comment by CisBetter** [comment]
In your output git is accessing the top-level Wurst directory. That usually means that the patch has not been applied. Did you run the apply-patch.bat script (which only works if your `mc `directory is already initialised) or did you run initialize.bat (which creates a git repository in `mc`; you should run this script first)?
