### ISSUE TITLE
AutoEat improvements

### ISSUE THREAD

**Issue by mmehnert** [Wurst-Imperium/Wurst-MC-1.10#66]
At the moment I can see the following things that could be improved about AutoEat:

* Currently food is selected by highest saturation and is being consumed as soon as  the hunger level is <20.  An option to 
  * eat the least available food would be nice to clear out inventory faster or
    * eat food with the smallest saturation instead of highest saturation and
  * eat food in a way that matches hunger level with food points per food item in order not to waste food would be very nice (Eat as soon as possible if health is not 100% and wait for hunger to increase until it matches the food points of the next preferred food if health is 100%. Also add an option to change the health threshold for this behaviour.).
* AutoEat is not aware of what other mods are doing. E.g. KillAura could activate the same time AutoEat is active which could mess up at least the state of one of these mods.

Most of these changes seem to be quite easy to implement by looking at the code. I may be able to do that somewhere around January. But I wanted to discuss these suggestions first and put out the ideas in case someone else has the time to do it first. 
Is there anything that would speak against including the suggestions I've described?

**Comment by CisBetter** [comment]
In #67 I've added the ability to eat food that gives low Food Points first.
![tmp](https://cloud.githubusercontent.com/assets/17952058/20400808/8bf49e96-acf6-11e6-9735-6083f1c5eea4.png)
Is this what you've expected when saying
> eat the least available food would be nice to clear out inventory faster

?

**Comment by mmehnert** [comment]
Nice! This is one of the options I'm suggesting.  "Least available" would be that you have a stack of one type and only 20 of another type. It may be preferable to eat the 20 first to free the inventory slot.

**Comment by mmehnert** [comment]
That would require three options that exclude each other:
  * High saturation first
  * Low saturation first
  * Use slot with lowest food item quantity first.

The other ideas mentioned above are independent of the food preferences.

**Comment by mmehnert** [comment]
The conflict with KillAura happens quite regularly, actually. Mostly when using a Mob grinder. AutoEat gets into an endless loop of eating that does not result in food consumption....
