### ISSUE TITLE
Wurst AI Conflicts with Jesus

### ISSUE THREAD

**Issue by Mhowser** [Wurst-Imperium/Wurst-MC-1.10#71]
.goto command does not work as desired when the jesus mod is enabled. also the AI appears to get stuck when moving from a 2-block tall body of water to a 1-block tall body, reqiuring the player to retype the command.

https://www.youtube.com/watch?v=rJq96y4P4HE

**Comment by Alexander01998** [comment]
You must enable Jesus before running `.goto`. It cannot (yet) react to changes made after the path is calculated.
